services:
  nginx:
    build: ./requirements/nginx/
    image: source_nginx
    container_name: nginx
    ports: 
      - 443:443
    volumes:
      - wordpress_data:/wordpress_page
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        MYSQL_USER: ${MYSQL_USER} 
        MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    image: source_mariadb
    container_name: mariadb
    ports: 
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
  wordpress:
    build:
      context: ./requirements/wordpress/
    image: source_wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/wordpress_page

volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      device: /home/becastro/data/database
      type: none
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      device: /home/becastro/data/wordpress
      type: none
