services:
  nginx:
    build: ./requirements/nginx/
    image: source_nginx
    container_name: nginx
    ports: 
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart:
      always
    depends_on:
      - wordpress
    networks:
      - inception
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        MYSQL_USER: ${MYSQL_USER} 
        MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    image: source_mariadb
    container_name: mariadb
    expose:
      - 3306
    volumes:
      - database:/var/lib/mysql
    restart:
      always
    networks:
      - inception
  wordpress:
    expose: 
      - 9000
    build:
      context: ./requirements/wordpress/
    environment:
        MYSQL_USER: ${MYSQL_USER} 
        MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME} 
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST} 
    image: source_wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart:
      always
    networks:
      - inception

volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      device: /home/$USER/data/database
      type: none
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      device: /home/$USER/data/wordpress
      type: none

networks:
  inception:
    driver: bridge
